Models/Alunos.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace escola.Models
{
    public class Alunos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get;set; }

        [DataType(DataType.Date)]
        public DateTime DataCadatro { get; set; }
        public string Turma { get; set; }

    }
}

Controllers/AlunosCandidatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using escola.Data;
using escola.Models;

namespace escola.Controllers
{
    public class AlunosCandidatosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlunosCandidatosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AlunosCandidatos
        public async Task<IActionResult> Index()
        {
              return View(await _context.AlunosCandidatos.ToListAsync());
        }

        // GET: AlunosCandidatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AlunosCandidatos == null)
            {
                return NotFound();
            }

            var alunosCandidatos = await _context.AlunosCandidatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alunosCandidatos == null)
            {
                return NotFound();
            }

            return View(alunosCandidatos);
        }

        // GET: AlunosCandidatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AlunosCandidatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,DataNascimento,Telefone,Email")] AlunosCandidatos alunosCandidatos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alunosCandidatos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alunosCandidatos);
        }

        // GET: AlunosCandidatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AlunosCandidatos == null)
            {
                return NotFound();
            }

            var alunosCandidatos = await _context.AlunosCandidatos.FindAsync(id);
            if (alunosCandidatos == null)
            {
                return NotFound();
            }
            return View(alunosCandidatos);
        }

        // POST: AlunosCandidatos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,DataNascimento,Telefone,Email")] AlunosCandidatos alunosCandidatos)
        {
            if (id != alunosCandidatos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alunosCandidatos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunosCandidatosExists(alunosCandidatos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alunosCandidatos);
        }

        // GET: AlunosCandidatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AlunosCandidatos == null)
            {
                return NotFound();
            }

            var alunosCandidatos = await _context.AlunosCandidatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alunosCandidatos == null)
            {
                return NotFound();
            }

            return View(alunosCandidatos);
        }

        // POST: AlunosCandidatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AlunosCandidatos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.AlunosCandidatos'  is null.");
            }
            var alunosCandidatos = await _context.AlunosCandidatos.FindAsync(id);
            if (alunosCandidatos != null)
            {
                _context.AlunosCandidatos.Remove(alunosCandidatos);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunosCandidatosExists(int id)
        {
          return _context.AlunosCandidatos.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Cadastrado()
        {
            return View();
        }
    }
}

Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using escola.Data;
using escola.Models;

namespace escola.Controllers
{
    public class AlunosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlunosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Alunos
        public async Task<IActionResult> Index()
        {
              return View(await _context.Alunos.ToListAsync());
        }

        // GET: Alunos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Alunos == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,DataCadatro,Turma")] Alunos alunos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alunos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Alunos == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos.FindAsync(id);
            if (alunos == null)
            {
                return NotFound();
            }
            return View(alunos);
        }

        // POST: Alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,DataCadatro,Turma")] Alunos alunos)
        {
            if (id != alunos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alunos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunosExists(alunos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Alunos == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Alunos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Alunos'  is null.");
            }
            var alunos = await _context.Alunos.FindAsync(id);
            if (alunos != null)
            {
                _context.Alunos.Remove(alunos);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunosExists(int id)
        {
          return _context.Alunos.Any(e => e.Id == id);
        }
    }
}

Views/Alunos/Create.cshtml
@model escola.Models.Alunos

@{
    ViewData["Title"] = "Create";
}

<h1 class="titulo1">Adicione um novo</h1>

<h4 class="titulo2">Alunos</h4>
<hr />
<div class="centralizar">

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div class="row">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group, col-6">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group col-6">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group, col-12">
                <label asp-for="DataCadatro" class="control-label"></label>
                <input asp-for="DataCadatro" class="form-control" />
                <span asp-validation-for="DataCadatro" class="text-danger"></span>
            </div>
            <div class="form-group, col-12">
                <label asp-for="Turma" class="control-label"></label>
                <input asp-for="Turma" class="form-control" />
                <span asp-validation-for="Turma" class="text-danger"></span>
            </div>
            </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary" style="width: 100%" />
                </div>
        </form>
            <br />
            <div>
                <a asp-action="Index" class="btn btn-danger" style="width: 100%">Voltar para lista</a>
            </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</div>

Views/Alunos/Delete.cshtml
@model escola.Models.Alunos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCadatro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCadatro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turma)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Alunos/Details.cshtml
@model escola.Models.Alunos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCadatro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCadatro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turma)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Alunos/Edit.cshtml
@model escola.Models.Alunos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCadatro" class="control-label"></label>
                <input asp-for="DataCadatro" class="form-control" />
                <span asp-validation-for="DataCadatro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turma" class="control-label"></label>
                <input asp-for="Turma" class="form-control" />
                <span asp-validation-for="Turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Alunos/Index.cshtml
@model IEnumerable<escola.Models.Alunos>

@{
    ViewData["Title"] = "Index";
}

<h1 class="titulo1">Index</h1>
<div class="centralizar">

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<p>
    <a asp-controller="AlunosCandidatos" asp-action="Index">Ver Candidatos</a>
</p>
    <table id ="myTable" class="table table-bordered table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadatro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadatro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turma)
            </td>
            <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="width:100%">
                            Ações
                        </button>
                        <ul class="dropdown-menu">
                            <li><a asp-action="Edit" asp-route-id="@item.Id" class="dropdown-item">Editar</a> </li>
                            <li> <a asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">Detalhes</a> </li>
                            <li> <a asp-action="Delete" asp-route-id="@item.Id" class="dropdown-item">Deletar</a></li>
                        </ul>
                    </div>
                </td>
        </tr>
}
    </tbody>
</table>
    @section Scripts{
            <script>
                $(document).ready(function () {
                    $('#myTable').DataTable();
                });
            </script>
    }
</div>