Models/ProfessoresCandidatos.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace escola.Models
{
    public class ProfessoresCandidatos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set;}

        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Linkedin { get; set; }  
    }
}

Controllers/ProfessoresCandidatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using escola.Data;
using escola.Models;

namespace escola.Controllers
{
    public class ProfessoresCandidatosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfessoresCandidatosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProfessoresCandidatos
        public async Task<IActionResult> Index()
        {
              return View(await _context.ProfessoresCandidatos.ToListAsync());
        }

        // GET: ProfessoresCandidatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProfessoresCandidatos == null)
            {
                return NotFound();
            }

            var professoresCandidatos = await _context.ProfessoresCandidatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professoresCandidatos == null)
            {
                return NotFound();
            }

            return View(professoresCandidatos);
        }

        // GET: ProfessoresCandidatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProfessoresCandidatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Sobrenome,DataNascimento,Telefone,Email,Linkedin")] ProfessoresCandidatos professoresCandidatos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professoresCandidatos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(professoresCandidatos);
        }

        // GET: ProfessoresCandidatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProfessoresCandidatos == null)
            {
                return NotFound();
            }

            var professoresCandidatos = await _context.ProfessoresCandidatos.FindAsync(id);
            if (professoresCandidatos == null)
            {
                return NotFound();
            }
            return View(professoresCandidatos);
        }

        // POST: ProfessoresCandidatos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Sobrenome,DataNascimento,Telefone,Email,Linkedin")] ProfessoresCandidatos professoresCandidatos)
        {
            if (id != professoresCandidatos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professoresCandidatos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessoresCandidatosExists(professoresCandidatos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professoresCandidatos);
        }

        // GET: ProfessoresCandidatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProfessoresCandidatos == null)
            {
                return NotFound();
            }

            var professoresCandidatos = await _context.ProfessoresCandidatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professoresCandidatos == null)
            {
                return NotFound();
            }

            return View(professoresCandidatos);
        }

        // POST: ProfessoresCandidatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProfessoresCandidatos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ProfessoresCandidatos'  is null.");
            }
            var professoresCandidatos = await _context.ProfessoresCandidatos.FindAsync(id);
            if (professoresCandidatos != null)
            {
                _context.ProfessoresCandidatos.Remove(professoresCandidatos);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessoresCandidatosExists(int id)
        {
          return _context.ProfessoresCandidatos.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Cadastrado()
        {
            return View();
        }
    }
}

Views/ProfessoresCandidatos/Cadastrado.cshtml
@{
    ViewData["Title"] = "Cadastrado";
}

<div class="centralizar">

<h1 class="titulo1">Cadastrado com Sucesso!</h1>

<a class="btn btn-primary" style="width: 100%" asp-area="" asp-controller="Home" asp-action="Index">Volte para a pagina principal</a>
</div>
                

Views/ProfessoresCandidatos/Create.cshtml
@model escola.Models.ProfessoresCandidatos

@{
    ViewData["Title"] = "Create";
}

<h1 class="titulo1">Candidate-se para</h1>

<h4 class="titulo2">Professor</h4>
<hr />
<div class="centralizar">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create">
                <div class="row">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group, col-6">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group, col-6">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group, col-12">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group, col-6">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group, col-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group, col-12">
                <label asp-for="Linkedin" class="control-label"></label>
                <input asp-for="Linkedin" class="form-control" />
                <span asp-validation-for="Linkedin" class="text-danger"></span>
            </div>
              <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" style="width: 100%" asp-action="Cadastrado" />
            </div>
                </div>
        </form>
        <br />
       
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

Views/ProfessoresCandidatos/Delete.cshtml
@model escola.Models.ProfessoresCandidatos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProfessoresCandidatos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Linkedin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Linkedin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ProfessoresCandidatos/Details.cshtml
@model escola.Models.ProfessoresCandidatos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProfessoresCandidatos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Linkedin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Linkedin)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ProfessoresCandidatos/Edit.cshtml
@model escola.Models.ProfessoresCandidatos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProfessoresCandidatos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Linkedin" class="control-label"></label>
                <input asp-for="Linkedin" class="form-control" />
                <span asp-validation-for="Linkedin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProfessoresCandidatos/Index.cshtml
@model IEnumerable<escola.Models.ProfessoresCandidatos>

@{
    ViewData["Title"] = "Index";
}

<h1 class="titulo1">Index</h1>

<div class="centralizar">
    <p>
        <a asp-controller="ProfessoresCandidatos" asp-action="Index">Ver Alunos</a>
    </p>
    <table id="myTable" class="table table-bordered table-dark">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Linkedin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Linkedin)
            </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="width:100%">
                                Ações
                            </button>
                            <ul class="dropdown-menu">
                                <li><a asp-action="Edit" asp-route-id="@item.Id" class="dropdown-item">Editar</a> </li>
                                <li> <a asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">Detalhes</a> </li>
                                <li> <a asp-action="Delete" asp-route-id="@item.Id" class="dropdown-item">Deletar</a></li>
                            </ul>
                        </div>
                    </td>
        </tr>
}
    </tbody>
</table>
    @section Scripts{
            <script>
                $(document).ready(function () {
                    $('#myTable').DataTable();
                });
            </script>
}
</div>